### ISSUE TITLE
Sidebar always scrolls to upside every select item in the sidebar and at the top of the sidebar menu texts are corrupted when scrolling down the sidebar

### ISSUE THREAD

**Issue by Gokhan1990** [mohammadoftadeh/oftadeh-react-admin#2]
Hello how to solve these 2 issues thank you.

**Comment by mohammadoftadeh** [comment]
Hi, please provide a clearer explanation, preferably with a picture or video.

**Comment by Gokhan1990** [comment]
[https://hizliresim.com/Ti4W59](url)

**Comment by Gokhan1990** [comment]
this one is first issue at the image corrupted texts... the second issue is if i click bottom sidebar items sidebar scrolling upside i wanted no scrolling but it goes at the top.

**Comment by mohammadoftadeh** [comment]
> [https://hizliresim.com/Ti4W59](url)

You can add `background-color` and `z-index` to fix this issue

**Comment by mohammadoftadeh** [comment]
> this one is first issue at the image corrupted texts... the second issue is if i click bottom sidebar items sidebar scrolling upside i wanted no scrolling but it goes at the

**Comment by mohammadoftadeh** [comment]
> > this one is first issue at the image corrupted texts... the second issue is if i click bottom sidebar items sidebar scrolling upside i wanted no scrolling but it goes at the

For the second issue, please mention it with a picture or a video

**Comment by Gokhan1990** [comment]
[https://hizliresim.com/N1N1dH](https://hizliresim.com/N1N1dH)

**Comment by Gokhan1990** [comment]
Hello Mohammad i added disableSticky prop to ListSubheader and text issue is solved. Thank you. 

The scroll issue is stil im working on it.

**Comment by mohammadoftadeh** [comment]
> https://hizliresim.com/N1N1dH

This feature is better to have and should not be changed. Now if you need to prevent this from happening, you should use JavaScript to prevent this from happening. for example (You can find and test other methods as well):

```
document.getElementById('#hakkinda').addEventListener('click', function (e) {
    e.preventDefault();
    doSomething();
});
```
